name: PlayerInfo
version: 1.3.3
author: Matthww
api: [3.0.0-ALPHA10, 3.0.0-ALPHA11, 3.0.0-ALPHA12]
description: Shows info about a certain player!
main: Matthww\PlayerInfo\PlayerInfo

commands:
 playerinfo:
  description: Show info about a certain player!
  usage: "/playerinfo <player>"
  permission: playerinfo.use
  aliases: ['pinfo']
permissions:
  playerinfo:
    default: false
    children:
      playerinfo.use:
        default: op
        description: "Allows the user to run the playerinfo command"
