name: PlayerInfo
version: 2.1.5
author: Matthww
api: 5.0.0
description: Shows information about a certain player!
main: Matthww\PlayerInfo\PlayerInfo

commands:
 playerinfo:
  description: Show information about a certain player!
  usage: "/playerinfo <player>"
  permission: playerinfo.use
  aliases: ['pinfo']

permissions:
  playerinfo.use:
    default: op
    description: "Allows the player to execute the playerinfo command"
