name: PlayerInfo
version: 2.1.5
author: Matthww
api: [4.0.0]
description: Shows info about a certain player!
main: Matthww\PlayerInfo\PlayerInfo

commands:
 playerinfo:
  description: Show info about a certain player!
  usage: "/playerinfo <player>"
  permission: playerinfo.use
  aliases: ['pinfo']
permissions:
   playerinfo.use:
     default: op
     description: "Allows the user to run the playerinfo command"
